---
- hosts: webservers 
  become: True
  tasks:
    - name: Initiate ansible
      debug:
        msg:  "mvn -f /var/lib/jenkins/workspace/ansible-demo1/pom.xml clean install package"
    - name: Initiate ansible
      shell: "/home/ec2-user/apache-maven-3.8.6/bin/mvn -f /var/lib/jenkins/workspace/ansible-demo1/pom.xml clean install package"
...
